import { Inter } from "next/font/google";

import "./globals.css";
import Script from "next/script";
import NavBar from "../../component/NavBar";
import Footer from "../../component/Footer";
import Head from "next/head";

import {Montserrat} from 'next/font/google'

const montserrat = Montserrat({
  subsets: ['latin'], 
  variable:'--font-mont'
})
export const metadata = {

  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({  children }) {
  return (

    <html lang="en">
      <Head>
      <meta name='viewport' content='width=device-width, initial-scale=1'/>
      <link rel='icon' href='/flavicon.ico'/> 
      <Script id='theme-switcher' strategy='beforeInteractive'>
                {`
            if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
              document.documentElement.classList.add('dark')
            } else {
              document.documentElement.classList.remove('dark')
            }
                
                `}
              </Script>
      </Head> 
       
        
      <body >
      <main className={`${montserrat.variable} font-mont text-lg dark:bg-dark  w-full min-h-screen`}>
   <NavBar/>
         {children}
        <Footer/>
      </main>
   


      </body>
    </html>
  );
}

